// vehiclesData.js
const vehicles = [
  {
    id: '1',
    name: 'Swift Dzire',
    image: 'dzir.jpg',
    description: 'Perfect for city driving',
    price: 'For local use (12 hr – 120km) Rate - ₹2400',
    after:'After exciding 120 km ₹12/km .',
    extra:'Extra hours - ₹200/hr . ',
    outstation:'Outstation (250 km minimum/day) Rate - ₹3000',
    extra2:'After exciding 250 km ₹12/km .',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night) .',
    alt: 'Tole tax & parking extra .',
  },
 
  {
    id: '2',
    name: 'Innova Crysta',
    image: 'inovacrysta.jpg',
    description: 'Premium experience',
    price: 'For local use (12 hr – 120km) Rate - ₹3600',
    after:'After exciding 120 km ₹18/km',
    extra:'Extra hours - ₹300/hr ',
    outstation:'Outstation (250 km minimum/day) Rate - ₹4500',
    extra2:'After exciding 250 km ₹18/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night)',
    alt: 'Tole tax & parking extra ',
  },
  
  {
    id: '3',
    name: 'Inova',
    image: 'inova.jpg',
    description: 'Want some comfort...',
    price: 'For local use (12 hr – 120km) Rate - ₹3000',
    after:'After exciding 120 km ₹16/km',
    extra:'Extra hours - ₹300/hr ',
    outstation:'Outstation (250 km minimum/day) Rate - ₹4000',
    extra2:'After exciding 250 km ₹16/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night)',
    alt: 'Tole tax & parking extra ',
  },
  {
    id: '4',
    name: 'Maruti Ertiga',
    image: 'ertiga.jpg',
    description: 'Best ride for short',
    price: 'For local use (12 hr – 120km) Rate - ₹2800',
    after:'After exciding 120 km ₹14/km',
    extra:'Extra hours - ₹200/hr ',
    outstation:'Outstation (250 minimum/day )rate - ₹3500',
    extra2:'After exciding 250 km ₹14/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night)',
    alt: 'Tole tax & parking extra ',
  },
  
  {
    id: '5',
    name: 'Tempo traveller (17 seater)',
    image: 'tampo.jpg',
    description: 'Best ride for long distance',
    price: 'For local use (12 hr – 120km) Rate - ₹8000',
    after:'After exciding 120 km ₹32/km',
    extra:'Extra hours - ₹500/hr ',
    outstation:'Outstation (250km minimum/day) Rate - ₹8000',
    extra2:'After exciding 250 km ₹32/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹500/night)',
    alt: 'Tole tax & parking extra ',
  },
  {
    id: '6',
    name: 'kia carens',
    image: 'kia.jpg',
    description: 'Best ride for long distance',
    price: 'For local use (12 hr – 120km) Rate - ₹3000',
    after:'After exciding 120 km ₹15/km',
    extra:'Extra hours - ₹200/hr ',
    outstation:'Outstation (250 km minimum/day) Rate - ₹3500',
    extra2:'After exciding 250 km ₹15/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night)',
    alt: 'Tole tax & parking extra ',
  },
  {
    id: '7',
    name: 'Honda city ',
    image: 'hondacity.jpg',
    description: 'Best ride for long distance',
    price: 'For local use (12 hr – 120km) Rate - ₹3200',
    after:'After exciding 120 km ₹16/km',
    extra:'Extra hours - ₹200/hr ',
    outstation:'Outstation (250 km minimum/day) Rate - ₹4000',
    extra2:'After exciding 250 km ₹16/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night)',
    alt: 'Tole tax & parking extra ',
  },

  {
    id: '8',
    name: 'Hyundai Verna ',
    image: 'varna.jpg',
    description: 'Best ride for long distance',
    price: 'For local use (12 hr – 120km) Rate - ₹3200',
    after:'After exciding 120 km ₹16/km',
    extra:'Extra hours - ₹200/hr ',
    outstation:'Outstation (250km minimum/day) rate - ₹4000',
    extra2:'After exciding 250 km ₹16/km',
    night:'Driver night charges -  before 6 Am – after 9 pm (₹300/night)',
    alt: 'Tole tax & parking extra ',
  },
];

export default vehicles;
